;; -*- mode: scheme; coding:utf-8 -*-
(define-library (extra-aes-vectors)
  (export extra-aes-ecb-vectors)
  (import (scheme base))
  (include "aes-ecb-test-vectors.scm"))
(load "test-lib/aeolus-test.sld")
(load "test-lib/aeolus-test.sld")
(load "test-lib/aeolus-test.sld")
(load "test-lib/aeolus-test.sld")
(load "test-lib/aeolus-test.sld")
